### ISSUE TITLE
Client can't change/edit recurring donation

### ISSUE THREAD

**Issue by microsyskl** [adixon/ca.civicrm.iats#20]
Test below is from a confirmation email client gets after setting up a recurring donation.  It provides a link for them to edit/change/delete this recurring donation but it just spits out an XML coded page.

Donors aren't happy because they can't change their recurring donation.  

I also have no means of going in and changing it either.

Currently using CiviCRM 4.6.13, iats 1.5.0

Test-drive Email / Receipt
This is a test-drive email. No live financial transaction has occurred.
Thank You for your gift to Operation Exodus USA
Please print this confirmation for your records.
Contribution Information 
Amount 	$ 1.00 
Date 	March 22nd, 2017 12:38 PM 
Transaction # 	A99EA286:1490200737 
This is a recurring contribution. You can cancel future contributions by visiting this web page. 
https://www.iatspayments.com/NetGate/ProcessLink.asmx?WSDL

You can update recurring contribution amount or change the number of installments for this recurring contribution by visiting this web page. 
https://www.iatspayments.com/NetGate/ProcessLink.asmx?WSDL

**Comment by adixon** [comment]
You are posting to an old repo, you should be using https://github.com/iATSPayments/com.iatspayments.civicrm

**Comment by microsyskl** [comment]
Thank you! IATS  pointed me to this link!


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Alan Dixon <notifications@github.com> Date: 3/22/17  1:22 PM  (GMT-05:00) To: "adixon/ca.civicrm.iats" <ca.civicrm.iats@noreply.github.com> Cc: microsyskl <ken@micro-systems.biz>, Author <author@noreply.github.com> Subject: Re: [adixon/ca.civicrm.iats] Client can't change/edit recurring donation (#20) 
You are posting to an old repo, you should be using https://github.com/iATSPayments/com.iatspayments.civicrm

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adixon/ca.civicrm.iats","title":"adixon/ca.civicrm.iats","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/adixon/ca.civicrm.iats"}},"updates":{"snippets":[{"icon":"PERSON","message":"@adixon in #20: You are posting to an old repo, you should be using https://github.com/iATSPayments/com.iatspayments.civicrm\r\n"}],"action":{"name":"View Issue","url":"https://github.com/adixon/ca.civicrm.iats/issues/20#issuecomment-288474297"}}}
